---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    createdBy: {{_author_}}
    createdOn: {{_date_}}
    description: Storage for {{_base_name_}}
  labels:
    app: {{_base_name_}}
    app.kubernetes.io/component: {{_base_name_}}
    app.kubernetes.io/instance: {{_base_name_}}
    app.kubernetes.io/name: {{_base_name_}}
    app.kubernetes.io/part-of: {{_base_name_}}
  name: {{_base_name_}}
  namespace: <++>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: <++>Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
