%% File: {{_file_name_}}
%% Written by: {{_author_}}
%% Created on: {{_date_}}
gitGraph
    commit
    commit
    branch develop
    checkout develop
    commit
    commit
    checkout main
    merge develop
    commit
    commit
