---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    createdBy: {{_author_}}
    createdOn: {{_date_}}
    description: Database for {{_base_name_}}
  labels:
    app: {{_base_name_}}
    app.kubernetes.io/component: {{_base_name_}}
    app.kubernetes.io/instance: {{_base_name_}}
    app.kubernetes.io/name: {{_base_name_}}
    app.kubernetes.io/part-of: {{_base_name_}}
  name: {{_base_name_}}
  namespace: <++>
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
