---
kind: PostgresCluster
apiVersion: postgres-operator.crunchydata.com/v1beta1
metadata:
  annotations:
    createdBy: {{_author_}}
    createdOn: {{_date_}}
    description: Database for {{_base_name_}}
  labels:
    app: {{_base_name_}}
    app.kubernetes.io/component: {{_base_name_}}
    app.kubernetes.io/instance: {{_base_name_}}
    app.kubernetes.io/name: {{_base_name_}}
    app.kubernetes.io/part-of: {{_base_name_}}
  name: {{_base_name_}}-db
  namespace: <++>
spec:
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.17-5
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            storageClassName: nfs-client
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: <++>Gi
  instances:
    - dataVolumeClaimSpec:
        storageClassName: nfs-client
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: <++>Gi
      replicas: 2
  users:
    - name: <++>
      options: "SUPERUSER"
      databases:
        - <++>
  postgresVersion: 13

