---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    createdBy: {{_author_}}
    createdOn: {{_date_}}
    description: <++>
    app: {{_base_name_}}
    app.kubernetes.io/component: {{_base_name_}}
    app.kubernetes.io/instance: {{_base_name_}}
    app.kubernetes.io/name: {{_base_name_}}
    app.kubernetes.io/part-of: {{_base_name_}}
  name: <++>
  namespace: <++>
