---
apiVersion: v1
kind: Service
metadata:
  annotations:
    createdBy: {{_author_}}
    createdOn: {{_date_}}
    description: Service for {{_base_name_}}
  labels:
    app: {{_base_name_}}
    app.kubernetes.io/component: {{_base_name_}}
    app.kubernetes.io/instance: {{_base_name_}}
    app.kubernetes.io/name: {{_base_name_}}
    app.kubernetes.io/part-of: {{_base_name_}}
  name: {{_base_name_}}
  namespace: <++>
spec:
  ports:
  - name: <++>
    port: <++>
    protocol: TCP
    targetPort: <++>
  selector:
    app: {{_base_name_}}
  sessionAffinity: None
  type: ClusterIP
